@startuml
'https://plantuml.com/class-diagram

class App{
    + start(Stage stage)
    + main(String[] args)
}

class date{
    -int year
    -int month
    -int year
    +date(int month, int day, int year)
    +getDateinString()
}

class Todo_List {
    - String title;
    - ArrayList<Item>items=new ArrayList<Item>()
    + Todo_List(String title)
    + Todo_List(String title,ArrayList<Item>items)
    + ArrayList<Item> addItem(Item addedElement)
    + ArrayList<Item> removeItem(int removeIndex)
    + ArrayList<Item> removeAllItems()
    + String getTitle()
    + String updateTitle(String newTitle)
    + ArrayList<Item>getItems()
    + ArrayList<Item>getIncompleteItems()
    + ArrayList<Item>getCompleteItems()
}

class Item{
       - String name;
       - String description;
       - date dueDate;
       - Boolean complete;
       + Item(boolean complete, String description, date dueDate, String name)
       + String getName()
       + void setDescription(String description)
       + String getDescription()
       + void setDate(date dueDate)
       + date getDate()
       + void setName(String name)
       + void setComplete(Boolean complete)
       + Boolean getComplete()
       + String updateDescription(String newDescription)
}

class Todo_Controller{
       - Todo_List Saved_todo=null;
       - Todo_List global_todo=null;
       - Todo_List Stored_todo_lists= null;
       - String file_name;
       - String file_path;
       - File xmlFile;
       + Todo_Controller(String path, String name) throws IOException
       + void setTodoList(Todo_List toAdd)
       + void setSavedTodoList(Todo_List toAdd)
       + Todo_List getTodoList()
       + Todo_List getSavedTodoList()
       + Todo_List getGlobal_todo()
       + Todo_List readMemory() throws IOException
       - String parseSingleLine(String Tag, String line)
}

@enduml